<?php
/* ImperiaMuCMS 2.0.7 | Desencriptado por TheKing027 - MTA | Más info: https://muteamargentina.com.ar */

echo "<h1 class=\"page-header\">Webshop Settings</h1>\r\n";
if (check_value($_POST["submit_changes"])) {
    savechanges();
}
loadModuleConfigs("webshop");
echo "<form action=\"\" method=\"post\">\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Status<br/><span>Enable/disable the webshop module.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_1", mconfig("active"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Gifts<br/><span>Enable/disable the gifting.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_2", mconfig("is_gift"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Global Settings Active<br/><span>Enable/disable the global settings.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_3", mconfig("is_global_active"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Excellent Options<br/><span>Working only if global settings are active.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_4\" value=\"";
echo mconfig("max_exc_opt");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Level<br/><span>Working only if global settings are active.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_5\" value=\"";
echo mconfig("max_lvl");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Life Option<br/><span>Working only if global settings are active.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_6\" value=\"";
echo mconfig("max_life_opt");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Sockets<br/><span>Working only if global settings are active.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_18\" value=\"";
echo mconfig("max_socket");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Payment Type<br/><span>Working only if global settings are active.<br>\r\n      1 - Platinum Coins, 2 - Gold Coins, 4 - Silver Coins (you can use combinations of values, for example:<br>\r\n      3 = Platinum & Gold Coins, 5 = Platinum & Silver Coins, 7 = All)</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_7\" value=\"";
echo mconfig("payment_type");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient System<br/><span>Enable/disable the ancient system.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_19", mconfig("is_anc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Harmony System<br/><span>Enable/disable the harmony system.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_8", mconfig("is_harmony"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Socket System<br/><span>Enable/disable the socket system.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_9", mconfig("is_socket"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Refinery System (380 lvl opts)<br/><span>Enable/disable the refinary system.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_10", mconfig("is_refinery"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Silver Coins Price Ratio<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_11\" value=\"";
echo mconfig("price_silver");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Gold Coins Price Ratio<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_12\" value=\"";
echo mconfig("price_gold");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Platinum Coins Price Ratio<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_13\" value=\"";
echo mconfig("price_platinum");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Ancient can use Harmony<br/><span>Enable/disable the harmony options for ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_20", mconfig("anc_harm"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient can be Excellent<br/><span>Enable/disable the excellent options for ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_21", mconfig("anc_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Socket can use Harmony<br/><span>Enable/disable the harmony options for socket items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_22", mconfig("sock_harm"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Socket can be Excellent<br/><span>Enable/disable the excellent options for socket items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_23", mconfig("sock_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow same Socket<br/><span>Enable/disable to choose same socket option in item.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_24", mconfig("allow_same_socket"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Bonus Socket<br/><span>Enable/disable option to choose bonus socket.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("allow_bonus_socket", mconfig("allow_bonus_socket"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Luck Price<br/><span>Choose price for luck.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_25\" value=\"";
echo mconfig("luck");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Skill Price<br/><span>Choose price for skill.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_26\" value=\"";
echo mconfig("skill");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Level Price<br/><span>Choose price for level.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_27\" value=\"";
echo mconfig("level");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Life Price<br/><span>Choose price for life.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_28\" value=\"";
echo mconfig("life");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Refinery Option Price<br/><span>Choose price for 380 lvl option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_29\" value=\"";
echo mconfig("refin");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient Tier 1 Price<br/><span>Choose price for ancient option tier 1.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Stamina +5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_30\" value=\"";
echo mconfig("anc11");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Stamina +10:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_31\" value=\"";
echo mconfig("anc12");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient Tier 2 Price<br/><span>Choose price for ancient option tier 2.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Stamina +5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_32\" value=\"";
echo mconfig("anc21");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Stamina +10:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_33\" value=\"";
echo mconfig("anc22");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Increase Mana per kill +8:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_34\" value=\"";
echo mconfig("exc11");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase hit points per kill +8:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_35\" value=\"";
echo mconfig("exc12");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase attacking(wizardly)speed +7:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_36\" value=\"";
echo mconfig("exc13");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase wizardly damage +2%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_37\" value=\"";
echo mconfig("exc14");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase Damage +level/20:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_38\" value=\"";
echo mconfig("exc15");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Excellent Damage Rate +10%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_39\" value=\"";
echo mconfig("exc16");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Increase Zen After Hunt +30%:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_40\" value=\"";
echo mconfig("exc21");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Defense success rate +10%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_41\" value=\"";
echo mconfig("exc22");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Reflect damage +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_42\" value=\"";
echo mconfig("exc23");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Damage Decrease +4%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_43\" value=\"";
echo mconfig("exc24");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase MaxMana +4%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_44\" value=\"";
echo mconfig("exc25");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase MaxHP +4%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_45\" value=\"";
echo mconfig("exc26");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Lv 2 Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">+125 HP:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_46\" value=\"";
echo mconfig("exc31");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>+125 Mana:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_47\" value=\"";
echo mconfig("exc32");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Ignore Enemy Defense 3%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_48\" value=\"";
echo mconfig("exc33");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>AG +50:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_49\" value=\"";
echo mconfig("exc34");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Attack(Wiz) Speed +5:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_50\" value=\"";
echo mconfig("exc35");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Lv 2.5 Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Ignore Enemy Defense 3%:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_62\" value=\"";
echo mconfig("exc71");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Life Recovery +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_63\" value=\"";
echo mconfig("exc72");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Lv 3 Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Ignore Enemy Defense 5%:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_51\" value=\"";
echo mconfig("exc41");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>5% Reflect Probabilities:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_52\" value=\"";
echo mconfig("exc42");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Life Recovery +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_53\" value=\"";
echo mconfig("exc43");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Mana Recovery +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_54\" value=\"";
echo mconfig("exc44");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Cape of Lord Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">+125 HP:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_55\" value=\"";
echo mconfig("exc51");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>+125 Mana:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_56\" value=\"";
echo mconfig("exc52");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Ignore Enemy Defense 3%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_57\" value=\"";
echo mconfig("exc53");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Increase command +85:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_58\" value=\"";
echo mconfig("exc54");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Cape of Fighter Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">+125 HP:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_59\" value=\"";
echo mconfig("exc61");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>+125 Mana:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_60\" value=\"";
echo mconfig("exc62");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Ignore Enemy Defense 3%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_61\" value=\"";
echo mconfig("exc63");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Wings Lv 4 #1 Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Chance of Fully Recovering Life +4%:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_64\" value=\"";
echo mconfig("exc81");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Chance of Damage from Breaking Enemy's Defense +4%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_65\" value=\"";
echo mconfig("exc82");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Chance of Double damage +4%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_66\" value=\"";
echo mconfig("exc83");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Lv 4 #2 Excellent Options Price<br/><span>Choose price for excellent options.</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Chance of Fully Recovering Mana +5%:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_67\" value=\"";
echo mconfig("exc91");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Chance of Fully Recovering Life +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_68\" value=\"";
echo mconfig("exc92");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Chance of Returning the Enemy's Attack Power +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_69\" value=\"";
echo mconfig("exc93");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td>Chance of Damage from Breaking Enemy's Defense +5%:</td>\r\n                        <td><input class=\"form-control\" type=\"text\" name=\"setting_70\" value=\"";
echo mconfig("exc94");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Element Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Max. Slots in Pentagram<br/><span>Select maximum available slots in pentagram. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_71\" value=\"";
echo mconfig("element_errtel_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Anger<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_72\" value=\"";
echo mconfig("element_anger_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Blessing<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_73\" value=\"";
echo mconfig("element_blessing_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Integrity<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_74\" value=\"";
echo mconfig("element_integrity_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Divinity<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_75\" value=\"";
echo mconfig("element_divinity_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Gale<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_76\" value=\"";
echo mconfig("element_gale_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: NONE<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_78\" value=\"";
echo mconfig("element_none_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: FIRE<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_79\" value=\"";
echo mconfig("element_fire_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: WATER<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_80\" value=\"";
echo mconfig("element_water_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: EARTH<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_81\" value=\"";
echo mconfig("element_earth_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: WIND<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_82\" value=\"";
echo mconfig("element_wind_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: DARKNESS<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_83\" value=\"";
echo mconfig("element_dark_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Anger<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_84\" value=\"";
echo mconfig("element_anger_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_85\" value=\"";
echo mconfig("element_anger_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_86\" value=\"";
echo mconfig("element_anger_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_87\" value=\"";
echo mconfig("element_anger_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_88\" value=\"";
echo mconfig("element_anger_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Blessing<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_89\" value=\"";
echo mconfig("element_blessing_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_90\" value=\"";
echo mconfig("element_blessing_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_91\" value=\"";
echo mconfig("element_blessing_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_92\" value=\"";
echo mconfig("element_blessing_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_93\" value=\"";
echo mconfig("element_blessing_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Integrity<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_94\" value=\"";
echo mconfig("element_integrity_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_95\" value=\"";
echo mconfig("element_integrity_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_96\" value=\"";
echo mconfig("element_integrity_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_97\" value=\"";
echo mconfig("element_integrity_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_98\" value=\"";
echo mconfig("element_integrity_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Divinity<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_99\" value=\"";
echo mconfig("element_divinity_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_100\" value=\"";
echo mconfig("element_divinity_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_101\" value=\"";
echo mconfig("element_divinity_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_102\" value=\"";
echo mconfig("element_divinity_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_103\" value=\"";
echo mconfig("element_divinity_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Gale<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_104\" value=\"";
echo mconfig("element_gale_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_105\" value=\"";
echo mconfig("element_gale_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_106\" value=\"";
echo mconfig("element_gale_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_107\" value=\"";
echo mconfig("element_gale_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_108\" value=\"";
echo mconfig("element_gale_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Anger Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_109\" value=\"";
echo mconfig("element_anger_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_110\" value=\"";
echo mconfig("element_anger_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_111\" value=\"";
echo mconfig("element_anger_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_112\" value=\"";
echo mconfig("element_anger_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_113\" value=\"";
echo mconfig("element_anger_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Blessing Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_114\" value=\"";
echo mconfig("element_blessing_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_115\" value=\"";
echo mconfig("element_blessing_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_116\" value=\"";
echo mconfig("element_blessing_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_117\" value=\"";
echo mconfig("element_blessing_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_118\" value=\"";
echo mconfig("element_blessing_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Integrity Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_119\" value=\"";
echo mconfig("element_integrity_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_120\" value=\"";
echo mconfig("element_integrity_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_121\" value=\"";
echo mconfig("element_integrity_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_122\" value=\"";
echo mconfig("element_integrity_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_123\" value=\"";
echo mconfig("element_integrity_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Divinity Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_124\" value=\"";
echo mconfig("element_divinity_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_125\" value=\"";
echo mconfig("element_divinity_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_126\" value=\"";
echo mconfig("element_divinity_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_127\" value=\"";
echo mconfig("element_divinity_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_128\" value=\"";
echo mconfig("element_divinity_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Gale Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_129\" value=\"";
echo mconfig("element_gale_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_130\" value=\"";
echo mconfig("element_gale_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_131\" value=\"";
echo mconfig("element_gale_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_132\" value=\"";
echo mconfig("element_gale_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_133\" value=\"";
echo mconfig("element_gale_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Anger<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_134\" value=\"";
echo mconfig("element_anger_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_135\" value=\"";
echo mconfig("element_anger_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_136\" value=\"";
echo mconfig("element_anger_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_137\" value=\"";
echo mconfig("element_anger_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_138\" value=\"";
echo mconfig("element_anger_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Blessing<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_139\" value=\"";
echo mconfig("element_blessing_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_140\" value=\"";
echo mconfig("element_blessing_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_141\" value=\"";
echo mconfig("element_blessing_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_142\" value=\"";
echo mconfig("element_blessing_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_143\" value=\"";
echo mconfig("element_blessing_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Integrity<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_144\" value=\"";
echo mconfig("element_integrity_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_145\" value=\"";
echo mconfig("element_integrity_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_146\" value=\"";
echo mconfig("element_integrity_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_147\" value=\"";
echo mconfig("element_integrity_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_148\" value=\"";
echo mconfig("element_integrity_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Divinity<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_149\" value=\"";
echo mconfig("element_divinity_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_150\" value=\"";
echo mconfig("element_divinity_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_151\" value=\"";
echo mconfig("element_divinity_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_152\" value=\"";
echo mconfig("element_divinity_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_153\" value=\"";
echo mconfig("element_divinity_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Gale<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_154\" value=\"";
echo mconfig("element_gale_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_155\" value=\"";
echo mconfig("element_gale_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_156\" value=\"";
echo mconfig("element_gale_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_157\" value=\"";
echo mconfig("element_gale_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_158\" value=\"";
echo mconfig("element_gale_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <input type=\"submit\" name=\"submit_changes\" value=\"Save Changes\" class=\"btn btn-success\"/>\r\n</form>";
function saveChanges()
{
    foreach ($_POST as $setting) {
        if (!check_value($setting)) {
            message("error", "Missing data (complete all fields).");
            return NULL;
        }
    }
    $xmlPath = __PATH_MODULE_CONFIGS__ . "webshop.xml";
    $xml = simplexml_load_file($xmlPath);
    $xml->active = $_POST["setting_1"];
    $xml->is_gift = $_POST["setting_2"];
    $xml->is_global_active = $_POST["setting_3"];
    $xml->max_exc_opt = $_POST["setting_4"];
    $xml->max_lvl = $_POST["setting_5"];
    $xml->max_life_opt = $_POST["setting_6"];
    $xml->payment_type = $_POST["setting_7"];
    $xml->is_harmony = $_POST["setting_8"];
    $xml->is_socket = $_POST["setting_9"];
    $xml->is_refinery = $_POST["setting_10"];
    $xml->price_silver = $_POST["setting_11"];
    $xml->price_gold = $_POST["setting_12"];
    $xml->price_platinum = $_POST["setting_13"];
    $xml->max_socket = $_POST["setting_18"];
    $xml->is_anc = $_POST["setting_19"];
    $xml->anc_harm = $_POST["setting_20"];
    $xml->anc_exc = $_POST["setting_21"];
    $xml->sock_harm = $_POST["setting_22"];
    $xml->sock_exc = $_POST["setting_23"];
    $xml->allow_same_socket = $_POST["setting_24"];
    $xml->allow_bonus_socket = $_POST["allow_bonus_socket"];
    $xml->luck = $_POST["setting_25"];
    $xml->skill = $_POST["setting_26"];
    $xml->level = $_POST["setting_27"];
    $xml->life = $_POST["setting_28"];
    $xml->refin = $_POST["setting_29"];
    $xml->anc11 = $_POST["setting_30"];
    $xml->anc12 = $_POST["setting_31"];
    $xml->anc21 = $_POST["setting_32"];
    $xml->anc22 = $_POST["setting_33"];
    $xml->exc11 = $_POST["setting_34"];
    $xml->exc12 = $_POST["setting_35"];
    $xml->exc13 = $_POST["setting_36"];
    $xml->exc14 = $_POST["setting_37"];
    $xml->exc15 = $_POST["setting_38"];
    $xml->exc16 = $_POST["setting_39"];
    $xml->exc21 = $_POST["setting_40"];
    $xml->exc22 = $_POST["setting_41"];
    $xml->exc23 = $_POST["setting_42"];
    $xml->exc24 = $_POST["setting_43"];
    $xml->exc25 = $_POST["setting_44"];
    $xml->exc26 = $_POST["setting_45"];
    $xml->exc31 = $_POST["setting_46"];
    $xml->exc32 = $_POST["setting_47"];
    $xml->exc33 = $_POST["setting_48"];
    $xml->exc34 = $_POST["setting_49"];
    $xml->exc35 = $_POST["setting_50"];
    $xml->exc41 = $_POST["setting_51"];
    $xml->exc42 = $_POST["setting_52"];
    $xml->exc43 = $_POST["setting_53"];
    $xml->exc44 = $_POST["setting_54"];
    $xml->exc51 = $_POST["setting_55"];
    $xml->exc52 = $_POST["setting_56"];
    $xml->exc53 = $_POST["setting_57"];
    $xml->exc54 = $_POST["setting_58"];
    $xml->exc61 = $_POST["setting_59"];
    $xml->exc62 = $_POST["setting_60"];
    $xml->exc63 = $_POST["setting_61"];
    $xml->exc71 = $_POST["setting_62"];
    $xml->exc72 = $_POST["setting_63"];
    $xml->exc81 = $_POST["setting_64"];
    $xml->exc82 = $_POST["setting_65"];
    $xml->exc83 = $_POST["setting_66"];
    $xml->exc91 = $_POST["setting_67"];
    $xml->exc92 = $_POST["setting_68"];
    $xml->exc93 = $_POST["setting_69"];
    $xml->exc94 = $_POST["setting_70"];
    $xml->element_errtel_slots = $_POST["setting_71"];
    $xml->element_anger_slots = $_POST["setting_72"];
    $xml->element_blessing_slots = $_POST["setting_73"];
    $xml->element_integrity_slots = $_POST["setting_74"];
    $xml->element_divinity_slots = $_POST["setting_75"];
    $xml->element_gale_slots = $_POST["setting_76"];
    $xml->element_none_price = $_POST["setting_78"];
    $xml->element_fire_price = $_POST["setting_79"];
    $xml->element_water_price = $_POST["setting_80"];
    $xml->element_earth_price = $_POST["setting_81"];
    $xml->element_wind_price = $_POST["setting_82"];
    $xml->element_dark_price = $_POST["setting_83"];
    $xml->element_anger_1_price = $_POST["setting_84"];
    $xml->element_anger_2_price = $_POST["setting_85"];
    $xml->element_anger_3_price = $_POST["setting_86"];
    $xml->element_anger_4_price = $_POST["setting_87"];
    $xml->element_anger_5_price = $_POST["setting_88"];
    $xml->element_blessing_1_price = $_POST["setting_89"];
    $xml->element_blessing_2_price = $_POST["setting_90"];
    $xml->element_blessing_3_price = $_POST["setting_91"];
    $xml->element_blessing_4_price = $_POST["setting_92"];
    $xml->element_blessing_5_price = $_POST["setting_93"];
    $xml->element_integrity_1_price = $_POST["setting_94"];
    $xml->element_integrity_2_price = $_POST["setting_95"];
    $xml->element_integrity_3_price = $_POST["setting_96"];
    $xml->element_integrity_4_price = $_POST["setting_97"];
    $xml->element_integrity_5_price = $_POST["setting_98"];
    $xml->element_divinity_1_price = $_POST["setting_99"];
    $xml->element_divinity_2_price = $_POST["setting_100"];
    $xml->element_divinity_3_price = $_POST["setting_101"];
    $xml->element_divinity_4_price = $_POST["setting_102"];
    $xml->element_divinity_5_price = $_POST["setting_103"];
    $xml->element_gale_1_price = $_POST["setting_104"];
    $xml->element_gale_2_price = $_POST["setting_105"];
    $xml->element_gale_3_price = $_POST["setting_106"];
    $xml->element_gale_4_price = $_POST["setting_107"];
    $xml->element_gale_5_price = $_POST["setting_108"];
    $xml->element_anger_1_price_level = $_POST["setting_109"];
    $xml->element_anger_2_price_level = $_POST["setting_110"];
    $xml->element_anger_3_price_level = $_POST["setting_111"];
    $xml->element_anger_4_price_level = $_POST["setting_112"];
    $xml->element_anger_5_price_level = $_POST["setting_113"];
    $xml->element_blessing_1_price_level = $_POST["setting_114"];
    $xml->element_blessing_2_price_level = $_POST["setting_115"];
    $xml->element_blessing_3_price_level = $_POST["setting_116"];
    $xml->element_blessing_4_price_level = $_POST["setting_117"];
    $xml->element_blessing_5_price_level = $_POST["setting_118"];
    $xml->element_integrity_1_price_level = $_POST["setting_119"];
    $xml->element_integrity_2_price_level = $_POST["setting_120"];
    $xml->element_integrity_3_price_level = $_POST["setting_121"];
    $xml->element_integrity_4_price_level = $_POST["setting_122"];
    $xml->element_integrity_5_price_level = $_POST["setting_123"];
    $xml->element_divinity_1_price_level = $_POST["setting_124"];
    $xml->element_divinity_2_price_level = $_POST["setting_125"];
    $xml->element_divinity_3_price_level = $_POST["setting_126"];
    $xml->element_divinity_4_price_level = $_POST["setting_127"];
    $xml->element_divinity_5_price_level = $_POST["setting_128"];
    $xml->element_gale_1_price_level = $_POST["setting_129"];
    $xml->element_gale_2_price_level = $_POST["setting_130"];
    $xml->element_gale_3_price_level = $_POST["setting_131"];
    $xml->element_gale_4_price_level = $_POST["setting_132"];
    $xml->element_gale_5_price_level = $_POST["setting_133"];
    $xml->element_anger_1_maxlvl = $_POST["setting_134"];
    $xml->element_anger_2_maxlvl = $_POST["setting_135"];
    $xml->element_anger_3_maxlvl = $_POST["setting_136"];
    $xml->element_anger_4_maxlvl = $_POST["setting_137"];
    $xml->element_anger_5_maxlvl = $_POST["setting_138"];
    $xml->element_blessing_1_maxlvl = $_POST["setting_139"];
    $xml->element_blessing_2_maxlvl = $_POST["setting_140"];
    $xml->element_blessing_3_maxlvl = $_POST["setting_141"];
    $xml->element_blessing_4_maxlvl = $_POST["setting_142"];
    $xml->element_blessing_5_maxlvl = $_POST["setting_143"];
    $xml->element_integrity_1_maxlvl = $_POST["setting_144"];
    $xml->element_integrity_2_maxlvl = $_POST["setting_145"];
    $xml->element_integrity_3_maxlvl = $_POST["setting_146"];
    $xml->element_integrity_4_maxlvl = $_POST["setting_147"];
    $xml->element_integrity_5_maxlvl = $_POST["setting_148"];
    $xml->element_divinity_1_maxlvl = $_POST["setting_149"];
    $xml->element_divinity_2_maxlvl = $_POST["setting_150"];
    $xml->element_divinity_3_maxlvl = $_POST["setting_151"];
    $xml->element_divinity_4_maxlvl = $_POST["setting_152"];
    $xml->element_divinity_5_maxlvl = $_POST["setting_153"];
    $xml->element_gale_1_maxlvl = $_POST["setting_154"];
    $xml->element_gale_2_maxlvl = $_POST["setting_155"];
    $xml->element_gale_3_maxlvl = $_POST["setting_156"];
    $xml->element_gale_4_maxlvl = $_POST["setting_157"];
    $xml->element_gale_5_maxlvl = $_POST["setting_158"];
    $save = $xml->asXML($xmlPath);
    if ($save) {
        message("success", "Settings successfully saved.");
    } else {
        message("error", "There has been an error while saving changes.");
    }
}

?>