<?php
/* ImperiaMuCMS 2.0.7 | Desencriptado por TheKing027 - MTA | Más info: https://muteamargentina.com.ar */

echo "<h1 class=\"page-header\">Webshop Settings</h1>\r\n";
if (check_value($_POST["submit_changes"])) {
    savechanges();
}
loadModuleConfigs("usercp.webshop");
$Items = new Items();
echo "<form action=\"\" method=\"post\">\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Status<br/><span>Enable/disable the webshop module.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("active", mconfig("active"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Global Discount<br/><span>Percentage discount for all purchases in Webshop. Example: 5 = 5% discount for whole purchase</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"global_discount\" value=\"";
echo mconfig("global_discount");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Gifts<br/><span>Enable/disable gifting.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_gifts", mconfig("enable_gifts"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Display Store Count<br/><span>Enable/disable displaying of store count.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("show_store_count", mconfig("show_store_count"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Display Total Bought<br/><span>Enable/disable displaying of total bought.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("show_total_bought", mconfig("show_total_bought"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Currency Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Platinum Coins<br/><span>Enable/disable usage of platinum coins in webshop.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_platinum", mconfig("enable_platinum"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Gold Coins<br/><span>Enable/disable usage of gold coins in webshop.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_gold", mconfig("enable_gold"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Silver Coins<br/><span>Enable/disable usage of silver coins in webshop.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_silver", mconfig("enable_silver"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>WCoins<br/><span>Enable/disable usage of WCoins in webshop.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_wcoin", mconfig("enable_wcoin"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Goblin Points<br/><span>Enable/disable usage of goblin points in webshop.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_gp", mconfig("enable_gp"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Default Currency<br/><span>Select default currency in webshop.</span></th>\r\n            <td>\r\n                <select name=\"default_currency\" class=\"form-control\">\r\n                    ";
if (mconfig("default_currency") == "1") {
    echo "<option value=\"1\" selected=\"selected\">Platinum Coins</option>";
} else {
    echo "<option value=\"1\">Platinum Coins</option>";
}
if (mconfig("default_currency") == "2") {
    echo "<option value=\"2\" selected=\"selected\">Gold Coins</option>";
} else {
    echo "<option value=\"2\">Gold Coins</option>";
}
if (mconfig("default_currency") == "3") {
    echo "<option value=\"3\" selected=\"selected\">Silver Coins</option>";
} else {
    echo "<option value=\"3\">Silver Coins</option>";
}
if (mconfig("default_currency") == "11") {
    echo "<option value=\"11\" selected=\"selected\">WCoins</option>";
} else {
    echo "<option value=\"11\">WCoins</option>";
}
if (mconfig("default_currency") == "13") {
    echo "<option value=\"13\" selected=\"selected\">Goblin Points</option>";
} else {
    echo "<option value=\"13\">Goblin Points</option>";
}
echo "                </select>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Platinum Coins Price Ratio<br/><span>Enter price ratio. Total price = Price * Ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"ratio_platinum\" value=\"";
echo mconfig("ratio_platinum");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Gold Coins Price Ratio<br/><span>Enter price ratio. Total price = Price * Ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"ratio_gold\" value=\"";
echo mconfig("ratio_gold");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Silver Coins Price Ratio<br/><span>Enter price ratio. Total price = Price * Ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"ratio_silver\" value=\"";
echo mconfig("ratio_silver");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>WCoins Price Ratio<br/><span>Enter price ratio. Total price = Price * Ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"ratio_wcoin\" value=\"";
echo mconfig("ratio_wcoin");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Goblin Points Price Ratio<br/><span>Enter price ratio. Total price = Price * Ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"ratio_gp\" value=\"";
echo mconfig("ratio_gp");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Items Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Max Level<br/><span>Enter maximum level of items (0 - 15). Value is overriden by column \"max_item_lvl\" in table IMPERIAMUCMS_WEBSHOP_ITEMS.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"max_level\" value=\"";
echo mconfig("max_level");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Life Options<br/><span>Enter maximum life options of items (0 - 7). Value is overriden by column \"max_item_opt\" in table IMPERIAMUCMS_WEBSHOP_ITEMS.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"max_life_opts\" value=\"";
echo mconfig("max_life_opts");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Excellent Options<br/><span>Enter maximum excellent options of items (0 - 6). Value is overriden by column \"max_exc_opt\" in table IMPERIAMUCMS_WEBSHOP_ITEMS.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"max_exc_opts\" value=\"";
echo mconfig("max_exc_opts");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max Socket Options<br/><span>Enter maximum socket options of items (0 - 5). Value is overriden by column \"max_socket\" in table IMPERIAMUCMS_WEBSHOP_ITEMS.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"max_sockets\" value=\"";
echo mconfig("max_sockets");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Bonus Socket Option<br/><span>Enable/disable bonus socket option.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_bonus_socket", mconfig("enable_bonus_socket"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Same Socket Options<br/><span>Enable/disable same socket options.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_same_socket", mconfig("enable_same_socket"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Harmony Option<br/><span>Enable/disable harmony option.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_harmony", mconfig("enable_harmony"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>380 lvl (Pink) Option<br/><span>Enable/disable 380 lvl option.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_380lvl", mconfig("enable_380lvl"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient Option<br/><span>Enable/disable ancient option.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_anc", mconfig("enable_anc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Harmony Option for Ancient Items<br/><span>Enable/disable harmony option for ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_anc_harm", mconfig("enable_anc_harm"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Excellent Options for Ancient Items<br/><span>Enable/disable excellent options for ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_anc_exc", mconfig("enable_anc_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Excellent Options for Socket Items<br/><span>Enable/disable excellent options for socket items.<br>Enable only for S6 - S9, on S10+ will cause issues with combination of new socket options. If you remove socket options with IDs greater than 255, can be used.</span>\r\n            </th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("enable_socket_exc", mconfig("enable_socket_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Basic Prices Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Luck Price<br/><span>Enter price of luck.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_luck\" value=\"";
echo mconfig("price_luck");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Skill Price<br/><span>Enter price of skill.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_skill\" value=\"";
echo mconfig("price_skill");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Level Price<br/><span>Enter price of level.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_level\" value=\"";
echo mconfig("price_level");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Life Price<br/><span>Enter price of life.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_life\" value=\"";
echo mconfig("price_life");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient Stamina Price<br/><span>Enter price of ancient stamina bonus.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_anc_stamina\" value=\"";
echo mconfig("price_anc_stamina");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>380 lvl Option Price<br/><span>Enter price of 380 lvl option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_380lvl\" value=\"";
echo mconfig("price_380lvl");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Items Excellent Options Prices Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        ";
$excOpts = loadexcopts();
foreach ($excOpts["items"] as $thisExc) {
    echo "\r\n        <tr>\r\n            <th>" . $thisExc["Name"] . " Price<br/><span>Enter price of item excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_item_" . $thisExc["ID"] . "\" value=\"" . mconfig("price_exc_opt_item_" . $thisExc["ID"]) . "\"/>\r\n            </td>\r\n        </tr>";
}
echo "\r\n    </table>\r\n    \r\n    <h3>Wings Excellent Options Prices Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">";
foreach ($excOpts["wings"] as $thisExc) {
    echo "\r\n        <tr>\r\n            <th>" . $thisExc["Name"] . " Price<br/><span>Enter price of wings excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_wings_" . $thisExc["ID"] . "\" value=\"" . mconfig("price_exc_opt_wings_" . $thisExc["ID"]) . "\"/>\r\n            </td>\r\n        </tr>";
}
echo "    </table>\r\n\r\n    <h3>4th Wings Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Max Excellent Options<br/><span>Select maximum excellent options.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"wings_4th_max_exc_opts\" value=\"";
echo mconfig("wings_4th_max_exc_opts");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Main Pentagram Option<br/><span>Enable/disable main pentagram option for 4th wings.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("wings_4th_main_opt", mconfig("wings_4th_main_opt"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Additional Pentagram Option<br/><span>Enable/disable additional pentagram option for 4th wings.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("wings_4th_add_opt", mconfig("wings_4th_add_opt"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Grade Level Price<br/><span>Select price per grade level.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_wings_4th_grade\" value=\"";
echo mconfig("price_exc_opt_wings_4th_grade");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        ";
$gradeOpts = $Items->loadGradeOptForItem();
foreach ($gradeOpts as $thisExc) {
    echo "\r\n        <tr>\r\n            <th>" . $thisExc["Name"] . " Price<br/><span>Enter price of 4th wings excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_wings_4th_" . $thisExc["Index"] . "\" value=\"" . mconfig("price_exc_opt_wings_4th_" . $thisExc["Index"]) . "\"/>\r\n            </td>\r\n        </tr>";
}
echo "        <tr>\r\n            <th>Main Pentagram Option Price<br/><span>Select price for main pentagram option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_pent_main_wings_4th\" value=\"";
echo mconfig("price_pent_main_wings_4th");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Main Pentagram Option Level Price<br/><span>Select price per level for main pentagram option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_pent_main_wings_4th_lvl\" value=\"";
echo mconfig("price_pent_main_wings_4th_lvl");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        ";
$additionalOpts = $Items->loadPentagramOptForWings();
foreach ($additionalOpts["add"] as $thisExc) {
    echo "\r\n        <tr>\r\n            <th>" . $thisExc["Name"] . " Price<br/><span>Enter price of 4th wings additional pentagram option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_pent_add_wings_4th_" . $thisExc["Index"] . "\" value=\"" . mconfig("price_pent_add_wings_4th_" . $thisExc["Index"]) . "\"/>\r\n            </td>\r\n        </tr>";
}
echo "        <tr>\r\n            <th>Additional Pentagram Option Level Price<br/><span>Select price per level for additional pentagram option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_pent_add_wings_4th_lvl\" value=\"";
echo mconfig("price_pent_add_wings_4th_lvl");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Earrings Price Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>(Left) Skill Damage Increase +17 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_l_0\" value=\"";
echo mconfig("price_exc_opt_earring_l_0");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Left) Attack Power / Wizardry Increase +20 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_l_1\" value=\"";
echo mconfig("price_exc_opt_earring_l_1");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Left) Excellent Damage Increase +35 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_l_2\" value=\"";
echo mconfig("price_exc_opt_earring_l_2");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Left) Critical Damage Increase +35 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_l_3\" value=\"";
echo mconfig("price_exc_opt_earring_l_3");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Left) Max Life Increase +200 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_l_4\" value=\"";
echo mconfig("price_exc_opt_earring_l_4");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Right) Attack Speed Increase +7 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_r_0\" value=\"";
echo mconfig("price_exc_opt_earring_r_0");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Right) Excellent Damage Chance Increase 4% Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_r_1\" value=\"";
echo mconfig("price_exc_opt_earring_r_1");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Right) Critical Damage Chance Increase 4% Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_r_2\" value=\"";
echo mconfig("price_exc_opt_earring_r_2");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Right) AG Auto Recovery Amount Increase +10 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_r_3\" value=\"";
echo mconfig("price_exc_opt_earring_r_3");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>(Right) Max Mana Increase +200 Price<br/><span>Select price of excellent option.</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"price_exc_opt_earring_r_4\" value=\"";
echo mconfig("price_exc_opt_earring_r_4");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h3>Element Settings</h3>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Max. Slots in Pentagram<br/><span>Select maximum available slots in pentagram. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_71\" value=\"";
echo mconfig("element_errtel_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Anger<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_72\" value=\"";
echo mconfig("element_anger_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Blessing<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_73\" value=\"";
echo mconfig("element_blessing_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Integrity<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_74\" value=\"";
echo mconfig("element_integrity_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Divinity<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_75\" value=\"";
echo mconfig("element_divinity_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Slots in Errtel of Gale<br/><span>Select maximum available slots in this errtel. Values: 0-5</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_76\" value=\"";
echo mconfig("element_gale_slots");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: NONE<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_78\" value=\"";
echo mconfig("element_none_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: FIRE<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_79\" value=\"";
echo mconfig("element_fire_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: WATER<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_80\" value=\"";
echo mconfig("element_water_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: EARTH<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_81\" value=\"";
echo mconfig("element_earth_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: WIND<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_82\" value=\"";
echo mconfig("element_wind_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Price of Element Type: DARKNESS<br/><span></span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_83\" value=\"";
echo mconfig("element_dark_price");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Anger<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_84\" value=\"";
echo mconfig("element_anger_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_85\" value=\"";
echo mconfig("element_anger_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_86\" value=\"";
echo mconfig("element_anger_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_87\" value=\"";
echo mconfig("element_anger_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_88\" value=\"";
echo mconfig("element_anger_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Blessing<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_89\" value=\"";
echo mconfig("element_blessing_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_90\" value=\"";
echo mconfig("element_blessing_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_91\" value=\"";
echo mconfig("element_blessing_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_92\" value=\"";
echo mconfig("element_blessing_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_93\" value=\"";
echo mconfig("element_blessing_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Integrity<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_94\" value=\"";
echo mconfig("element_integrity_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_95\" value=\"";
echo mconfig("element_integrity_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_96\" value=\"";
echo mconfig("element_integrity_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_97\" value=\"";
echo mconfig("element_integrity_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_98\" value=\"";
echo mconfig("element_integrity_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Divinity<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_99\" value=\"";
echo mconfig("element_divinity_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_100\" value=\"";
echo mconfig("element_divinity_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_101\" value=\"";
echo mconfig("element_divinity_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_102\" value=\"";
echo mconfig("element_divinity_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_103\" value=\"";
echo mconfig("element_divinity_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Gale<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_104\" value=\"";
echo mconfig("element_gale_1_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_105\" value=\"";
echo mconfig("element_gale_2_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_106\" value=\"";
echo mconfig("element_gale_3_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_107\" value=\"";
echo mconfig("element_gale_4_price");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_108\" value=\"";
echo mconfig("element_gale_5_price");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Anger Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_109\" value=\"";
echo mconfig("element_anger_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_110\" value=\"";
echo mconfig("element_anger_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_111\" value=\"";
echo mconfig("element_anger_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_112\" value=\"";
echo mconfig("element_anger_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_113\" value=\"";
echo mconfig("element_anger_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Blessing Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_114\" value=\"";
echo mconfig("element_blessing_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_115\" value=\"";
echo mconfig("element_blessing_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_116\" value=\"";
echo mconfig("element_blessing_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_117\" value=\"";
echo mconfig("element_blessing_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_118\" value=\"";
echo mconfig("element_blessing_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Integrity Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_119\" value=\"";
echo mconfig("element_integrity_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_120\" value=\"";
echo mconfig("element_integrity_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_121\" value=\"";
echo mconfig("element_integrity_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_122\" value=\"";
echo mconfig("element_integrity_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_123\" value=\"";
echo mconfig("element_integrity_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Divinity Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_124\" value=\"";
echo mconfig("element_divinity_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_125\" value=\"";
echo mconfig("element_divinity_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_126\" value=\"";
echo mconfig("element_divinity_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_127\" value=\"";
echo mconfig("element_divinity_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_128\" value=\"";
echo mconfig("element_divinity_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Prices of Errtel of Gale Level<br/><span></span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_129\" value=\"";
echo mconfig("element_gale_1_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_130\" value=\"";
echo mconfig("element_gale_2_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_131\" value=\"";
echo mconfig("element_gale_3_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_132\" value=\"";
echo mconfig("element_gale_4_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_133\" value=\"";
echo mconfig("element_gale_5_price_level");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Anger<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_134\" value=\"";
echo mconfig("element_anger_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_135\" value=\"";
echo mconfig("element_anger_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_136\" value=\"";
echo mconfig("element_anger_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_137\" value=\"";
echo mconfig("element_anger_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_138\" value=\"";
echo mconfig("element_anger_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Blessing<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_139\" value=\"";
echo mconfig("element_blessing_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_140\" value=\"";
echo mconfig("element_blessing_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_141\" value=\"";
echo mconfig("element_blessing_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_142\" value=\"";
echo mconfig("element_blessing_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_143\" value=\"";
echo mconfig("element_blessing_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Integrity<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_144\" value=\"";
echo mconfig("element_integrity_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_145\" value=\"";
echo mconfig("element_integrity_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_146\" value=\"";
echo mconfig("element_integrity_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_147\" value=\"";
echo mconfig("element_integrity_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_148\" value=\"";
echo mconfig("element_integrity_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Divinity<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_149\" value=\"";
echo mconfig("element_divinity_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_150\" value=\"";
echo mconfig("element_divinity_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_151\" value=\"";
echo mconfig("element_divinity_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_152\" value=\"";
echo mconfig("element_divinity_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_153\" value=\"";
echo mconfig("element_divinity_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Max. Level of Option in Errtel of Gale<br/><span>Values: 0-10</span></th>\r\n            <td>\r\n                <table width=\"100%\">\r\n                    <tr>\r\n                        <td width=\"50%\">Option 1:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_154\" value=\"";
echo mconfig("element_gale_1_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 2:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_155\" value=\"";
echo mconfig("element_gale_2_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 3:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_156\" value=\"";
echo mconfig("element_gale_3_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 4:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_157\" value=\"";
echo mconfig("element_gale_4_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                    <tr>\r\n                        <td width=\"50%\">Option 5:</td>\r\n                        <td width=\"50%\"><input class=\"form-control\" type=\"text\" name=\"setting_158\" value=\"";
echo mconfig("element_gale_5_maxlvl");
echo "\"/></td>\r\n                    </tr>\r\n                </table>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n    <input type=\"submit\" name=\"submit_changes\" value=\"Save Changes\" class=\"btn btn-success\"/>\r\n</form>";
function saveChanges()
{
    foreach ($_POST as $setting) {
        if (!check_value($setting)) {
            message("error", "Missing data (complete all fields).");
            return NULL;
        }
    }
    $xmlPath = __PATH_MODULE_CONFIGS__ . "usercp.webshop.xml";
    $xml = simplexml_load_file($xmlPath);
    $xml->active = $_POST["active"];
    $xml->global_discount = $_POST["global_discount"];
    $xml->show_store_count = $_POST["show_store_count"];
    $xml->show_total_bought = $_POST["show_total_bought"];
    $xml->enable_platinum = $_POST["enable_platinum"];
    $xml->enable_gold = $_POST["enable_gold"];
    $xml->enable_silver = $_POST["enable_silver"];
    $xml->enable_wcoin = $_POST["enable_wcoin"];
    $xml->enable_gp = $_POST["enable_gp"];
    $xml->default_currency = $_POST["default_currency"];
    $xml->ratio_platinum = $_POST["ratio_platinum"];
    $xml->ratio_gold = $_POST["ratio_gold"];
    $xml->ratio_silver = $_POST["ratio_silver"];
    $xml->ratio_wcoin = $_POST["ratio_wcoin"];
    $xml->ratio_gp = $_POST["ratio_gp"];
    $xml->enable_gifts = $_POST["enable_gifts"];
    $xml->max_level = $_POST["max_level"];
    $xml->max_life_opts = $_POST["max_life_opts"];
    $xml->max_exc_opts = $_POST["max_exc_opts"];
    $xml->max_sockets = $_POST["max_sockets"];
    $xml->enable_bonus_socket = $_POST["enable_bonus_socket"];
    $xml->enable_same_socket = $_POST["enable_same_socket"];
    $xml->enable_harmony = $_POST["enable_harmony"];
    $xml->enable_380lvl = $_POST["enable_380lvl"];
    $xml->enable_anc = $_POST["enable_anc"];
    $xml->enable_anc_harm = $_POST["enable_anc_harm"];
    $xml->enable_anc_exc = $_POST["enable_anc_exc"];
    $xml->enable_socket_exc = $_POST["enable_socket_exc"];
    $xml->price_luck = $_POST["price_luck"];
    $xml->price_skill = $_POST["price_skill"];
    $xml->price_level = $_POST["price_level"];
    $xml->price_life = $_POST["price_life"];
    $xml->price_anc_stamina = $_POST["price_anc_stamina"];
    $xml->price_380lvl = $_POST["price_380lvl"];
    $xml->price_exc_opt_item_0 = $_POST["price_exc_opt_item_0"];
    $xml->price_exc_opt_item_1 = $_POST["price_exc_opt_item_1"];
    $xml->price_exc_opt_item_2 = $_POST["price_exc_opt_item_2"];
    $xml->price_exc_opt_item_3 = $_POST["price_exc_opt_item_3"];
    $xml->price_exc_opt_item_4 = $_POST["price_exc_opt_item_4"];
    $xml->price_exc_opt_item_5 = $_POST["price_exc_opt_item_5"];
    $xml->price_exc_opt_item_6 = $_POST["price_exc_opt_item_6"];
    $xml->price_exc_opt_item_7 = $_POST["price_exc_opt_item_7"];
    $xml->price_exc_opt_item_8 = $_POST["price_exc_opt_item_8"];
    $xml->price_exc_opt_item_9 = $_POST["price_exc_opt_item_9"];
    $xml->price_exc_opt_item_10 = $_POST["price_exc_opt_item_10"];
    $xml->price_exc_opt_item_11 = $_POST["price_exc_opt_item_11"];
    $xml->price_exc_opt_item_12 = $_POST["price_exc_opt_item_12"];
    $xml->price_exc_opt_item_13 = $_POST["price_exc_opt_item_13"];
    $xml->price_exc_opt_item_14 = $_POST["price_exc_opt_item_14"];
    $xml->price_exc_opt_item_15 = $_POST["price_exc_opt_item_15"];
    $xml->price_exc_opt_item_16 = $_POST["price_exc_opt_item_16"];
    $xml->price_exc_opt_item_17 = $_POST["price_exc_opt_item_17"];
    $xml->price_exc_opt_item_18 = $_POST["price_exc_opt_item_18"];
    $xml->price_exc_opt_wings_0 = $_POST["price_exc_opt_wings_0"];
    $xml->price_exc_opt_wings_1 = $_POST["price_exc_opt_wings_1"];
    $xml->price_exc_opt_wings_2 = $_POST["price_exc_opt_wings_2"];
    $xml->price_exc_opt_wings_3 = $_POST["price_exc_opt_wings_3"];
    $xml->price_exc_opt_wings_4 = $_POST["price_exc_opt_wings_4"];
    $xml->price_exc_opt_wings_5 = $_POST["price_exc_opt_wings_5"];
    $xml->price_exc_opt_wings_6 = $_POST["price_exc_opt_wings_6"];
    $xml->price_exc_opt_wings_7 = $_POST["price_exc_opt_wings_7"];
    $xml->price_exc_opt_wings_8 = $_POST["price_exc_opt_wings_8"];
    $xml->price_exc_opt_wings_9 = $_POST["price_exc_opt_wings_9"];
    $xml->price_exc_opt_wings_10 = $_POST["price_exc_opt_wings_10"];
    $xml->price_exc_opt_wings_11 = $_POST["price_exc_opt_wings_11"];
    $xml->price_exc_opt_wings_12 = $_POST["price_exc_opt_wings_12"];
    $xml->price_exc_opt_wings_13 = $_POST["price_exc_opt_wings_13"];
    $xml->price_exc_opt_wings_14 = $_POST["price_exc_opt_wings_14"];
    $xml->price_exc_opt_wings_15 = $_POST["price_exc_opt_wings_15"];
    $xml->price_exc_opt_wings_16 = $_POST["price_exc_opt_wings_16"];
    $xml->price_exc_opt_wings_17 = $_POST["price_exc_opt_wings_17"];
    $xml->price_exc_opt_wings_18 = $_POST["price_exc_opt_wings_18"];
    $xml->price_exc_opt_wings_19 = $_POST["price_exc_opt_wings_19"];
    $xml->price_exc_opt_wings_20 = $_POST["price_exc_opt_wings_20"];
    $xml->price_exc_opt_wings_21 = $_POST["price_exc_opt_wings_21"];
    $xml->price_exc_opt_wings_22 = $_POST["price_exc_opt_wings_22"];
    $xml->price_exc_opt_wings_23 = $_POST["price_exc_opt_wings_23"];
    $xml->price_exc_opt_wings_24 = $_POST["price_exc_opt_wings_24"];
    $xml->wings_4th_max_exc_opts = $_POST["wings_4th_max_exc_opts"];
    $xml->wings_4th_main_opt = $_POST["wings_4th_main_opt"];
    $xml->wings_4th_add_opt = $_POST["wings_4th_add_opt"];
    $xml->price_exc_opt_wings_4th_grade = $_POST["price_exc_opt_wings_4th_grade"];
    $xml->price_exc_opt_wings_4th_0 = $_POST["price_exc_opt_wings_4th_0"];
    $xml->price_exc_opt_wings_4th_1 = $_POST["price_exc_opt_wings_4th_1"];
    $xml->price_exc_opt_wings_4th_2 = $_POST["price_exc_opt_wings_4th_2"];
    $xml->price_exc_opt_wings_4th_3 = $_POST["price_exc_opt_wings_4th_3"];
    $xml->price_exc_opt_wings_4th_4 = $_POST["price_exc_opt_wings_4th_4"];
    $xml->price_exc_opt_wings_4th_5 = $_POST["price_exc_opt_wings_4th_5"];
    $xml->price_exc_opt_wings_4th_6 = $_POST["price_exc_opt_wings_4th_6"];
    $xml->price_exc_opt_wings_4th_7 = $_POST["price_exc_opt_wings_4th_7"];
    $xml->price_exc_opt_wings_4th_8 = $_POST["price_exc_opt_wings_4th_8"];
    $xml->price_exc_opt_wings_4th_9 = $_POST["price_exc_opt_wings_4th_9"];
    $xml->price_exc_opt_wings_4th_10 = $_POST["price_exc_opt_wings_4th_10"];
    $xml->price_pent_main_wings_4th = $_POST["price_pent_main_wings_4th"];
    $xml->price_pent_main_wings_4th_lvl = $_POST["price_pent_main_wings_4th_lvl"];
    $xml->price_pent_add_wings_4th_0 = $_POST["price_pent_add_wings_4th_0"];
    $xml->price_pent_add_wings_4th_1 = $_POST["price_pent_add_wings_4th_1"];
    $xml->price_pent_add_wings_4th_2 = $_POST["price_pent_add_wings_4th_2"];
    $xml->price_pent_add_wings_4th_3 = $_POST["price_pent_add_wings_4th_3"];
    $xml->price_pent_add_wings_4th_4 = $_POST["price_pent_add_wings_4th_4"];
    $xml->price_pent_add_wings_4th_5 = $_POST["price_pent_add_wings_4th_5"];
    $xml->price_pent_add_wings_4th_6 = $_POST["price_pent_add_wings_4th_6"];
    $xml->price_pent_add_wings_4th_lvl = $_POST["price_pent_add_wings_4th_lvl"];
    $xml->price_exc_opt_earring_l_0 = $_POST["price_exc_opt_earring_l_0"];
    $xml->price_exc_opt_earring_l_1 = $_POST["price_exc_opt_earring_l_1"];
    $xml->price_exc_opt_earring_l_2 = $_POST["price_exc_opt_earring_l_2"];
    $xml->price_exc_opt_earring_l_3 = $_POST["price_exc_opt_earring_l_3"];
    $xml->price_exc_opt_earring_l_4 = $_POST["price_exc_opt_earring_l_4"];
    $xml->price_exc_opt_earring_r_0 = $_POST["price_exc_opt_earring_r_0"];
    $xml->price_exc_opt_earring_r_1 = $_POST["price_exc_opt_earring_r_1"];
    $xml->price_exc_opt_earring_r_2 = $_POST["price_exc_opt_earring_r_2"];
    $xml->price_exc_opt_earring_r_3 = $_POST["price_exc_opt_earring_r_3"];
    $xml->price_exc_opt_earring_r_4 = $_POST["price_exc_opt_earring_r_4"];
    $xml->element_errtel_slots = $_POST["setting_71"];
    $xml->element_anger_slots = $_POST["setting_72"];
    $xml->element_blessing_slots = $_POST["setting_73"];
    $xml->element_integrity_slots = $_POST["setting_74"];
    $xml->element_divinity_slots = $_POST["setting_75"];
    $xml->element_gale_slots = $_POST["setting_76"];
    $xml->element_none_price = $_POST["setting_78"];
    $xml->element_fire_price = $_POST["setting_79"];
    $xml->element_water_price = $_POST["setting_80"];
    $xml->element_earth_price = $_POST["setting_81"];
    $xml->element_wind_price = $_POST["setting_82"];
    $xml->element_dark_price = $_POST["setting_83"];
    $xml->element_anger_1_price = $_POST["setting_84"];
    $xml->element_anger_2_price = $_POST["setting_85"];
    $xml->element_anger_3_price = $_POST["setting_86"];
    $xml->element_anger_4_price = $_POST["setting_87"];
    $xml->element_anger_5_price = $_POST["setting_88"];
    $xml->element_blessing_1_price = $_POST["setting_89"];
    $xml->element_blessing_2_price = $_POST["setting_90"];
    $xml->element_blessing_3_price = $_POST["setting_91"];
    $xml->element_blessing_4_price = $_POST["setting_92"];
    $xml->element_blessing_5_price = $_POST["setting_93"];
    $xml->element_integrity_1_price = $_POST["setting_94"];
    $xml->element_integrity_2_price = $_POST["setting_95"];
    $xml->element_integrity_3_price = $_POST["setting_96"];
    $xml->element_integrity_4_price = $_POST["setting_97"];
    $xml->element_integrity_5_price = $_POST["setting_98"];
    $xml->element_divinity_1_price = $_POST["setting_99"];
    $xml->element_divinity_2_price = $_POST["setting_100"];
    $xml->element_divinity_3_price = $_POST["setting_101"];
    $xml->element_divinity_4_price = $_POST["setting_102"];
    $xml->element_divinity_5_price = $_POST["setting_103"];
    $xml->element_gale_1_price = $_POST["setting_104"];
    $xml->element_gale_2_price = $_POST["setting_105"];
    $xml->element_gale_3_price = $_POST["setting_106"];
    $xml->element_gale_4_price = $_POST["setting_107"];
    $xml->element_gale_5_price = $_POST["setting_108"];
    $xml->element_anger_1_price_level = $_POST["setting_109"];
    $xml->element_anger_2_price_level = $_POST["setting_110"];
    $xml->element_anger_3_price_level = $_POST["setting_111"];
    $xml->element_anger_4_price_level = $_POST["setting_112"];
    $xml->element_anger_5_price_level = $_POST["setting_113"];
    $xml->element_blessing_1_price_level = $_POST["setting_114"];
    $xml->element_blessing_2_price_level = $_POST["setting_115"];
    $xml->element_blessing_3_price_level = $_POST["setting_116"];
    $xml->element_blessing_4_price_level = $_POST["setting_117"];
    $xml->element_blessing_5_price_level = $_POST["setting_118"];
    $xml->element_integrity_1_price_level = $_POST["setting_119"];
    $xml->element_integrity_2_price_level = $_POST["setting_120"];
    $xml->element_integrity_3_price_level = $_POST["setting_121"];
    $xml->element_integrity_4_price_level = $_POST["setting_122"];
    $xml->element_integrity_5_price_level = $_POST["setting_123"];
    $xml->element_divinity_1_price_level = $_POST["setting_124"];
    $xml->element_divinity_2_price_level = $_POST["setting_125"];
    $xml->element_divinity_3_price_level = $_POST["setting_126"];
    $xml->element_divinity_4_price_level = $_POST["setting_127"];
    $xml->element_divinity_5_price_level = $_POST["setting_128"];
    $xml->element_gale_1_price_level = $_POST["setting_129"];
    $xml->element_gale_2_price_level = $_POST["setting_130"];
    $xml->element_gale_3_price_level = $_POST["setting_131"];
    $xml->element_gale_4_price_level = $_POST["setting_132"];
    $xml->element_gale_5_price_level = $_POST["setting_133"];
    $xml->element_anger_1_maxlvl = $_POST["setting_134"];
    $xml->element_anger_2_maxlvl = $_POST["setting_135"];
    $xml->element_anger_3_maxlvl = $_POST["setting_136"];
    $xml->element_anger_4_maxlvl = $_POST["setting_137"];
    $xml->element_anger_5_maxlvl = $_POST["setting_138"];
    $xml->element_blessing_1_maxlvl = $_POST["setting_139"];
    $xml->element_blessing_2_maxlvl = $_POST["setting_140"];
    $xml->element_blessing_3_maxlvl = $_POST["setting_141"];
    $xml->element_blessing_4_maxlvl = $_POST["setting_142"];
    $xml->element_blessing_5_maxlvl = $_POST["setting_143"];
    $xml->element_integrity_1_maxlvl = $_POST["setting_144"];
    $xml->element_integrity_2_maxlvl = $_POST["setting_145"];
    $xml->element_integrity_3_maxlvl = $_POST["setting_146"];
    $xml->element_integrity_4_maxlvl = $_POST["setting_147"];
    $xml->element_integrity_5_maxlvl = $_POST["setting_148"];
    $xml->element_divinity_1_maxlvl = $_POST["setting_149"];
    $xml->element_divinity_2_maxlvl = $_POST["setting_150"];
    $xml->element_divinity_3_maxlvl = $_POST["setting_151"];
    $xml->element_divinity_4_maxlvl = $_POST["setting_152"];
    $xml->element_divinity_5_maxlvl = $_POST["setting_153"];
    $xml->element_gale_1_maxlvl = $_POST["setting_154"];
    $xml->element_gale_2_maxlvl = $_POST["setting_155"];
    $xml->element_gale_3_maxlvl = $_POST["setting_156"];
    $xml->element_gale_4_maxlvl = $_POST["setting_157"];
    $xml->element_gale_5_maxlvl = $_POST["setting_158"];
    $save = $xml->asXML($xmlPath);
    if ($save) {
        message("success", "Settings successfully saved.");
    } else {
        message("error", "There has been an error while saving changes.");
    }
}
function loadExcOpts()
{
    $return = [];
    $xml = simplexml_load_file(__PATH_INCLUDES__ . "files/IGCN/ExcellentOptions.xml");
    if ($xml !== false) {
        $i = 0;
        foreach ($xml->Common->children() as $tag => $option) {
            $return["items"][$i]["ID"] = intval($option["ID"]);
            $return["items"][$i]["Number"] = intval($option["Number"]);
            $return["items"][$i]["Operator"] = intval($option["Operator"]);
            $return["items"][$i]["Value"] = intval($option["Value"]);
            $return["items"][$i]["FormulaID"] = intval($option["FormulaID"]);
            $return["items"][$i]["Name"] = strval($option["Name"]);
            $i++;
        }
        foreach ($xml->Wings->children() as $tag => $option) {
            $return["wings"][$i]["ID"] = intval($option["ID"]);
            $return["wings"][$i]["Number"] = intval($option["Number"]);
            $return["wings"][$i]["Operator"] = intval($option["Operator"]);
            $return["wings"][$i]["Value"] = intval($option["Value"]);
            $return["wings"][$i]["FormulaID"] = intval($option["FormulaID"]);
            $return["wings"][$i]["Name"] = strval($option["Name"]);
            $i++;
        }
        return $return;
    }
}

?>