<?php

$main_menu = array(
    // Premium Services
    lang('myaccount_txt_21', true) => array(
        "section_active" => true,
        "modules" => array(
            "donation" => array(
                "module" => "donation",
                "icon" => "icon-donate",
                "config" => "donation",
                "name" => lang('myaccount_txt_22', true),
                "desc" => lang('myaccount_txt_23', true),
                "hidden" => false,
            ),
            "vip" => array(
                "module" => "usercp/vip",
                "icon" => "icon-vip",
                "config" => "usercp.vip",
                "name" => lang('myaccount_txt_24', true),
                "desc" => lang('myaccount_txt_25', true),
                "hidden" => false,
            ),
            "webshop" => array(
                "module" => "webshop",
                "icon" => "icon-webshop",
                "config" => "webshop",
                "name" => lang('myaccount_txt_26', true),
                "desc" => lang('myaccount_txt_27', true),
                "hidden" => false,
            ),
            "vote" => array(
                "module" => "usercp/vote",
                "icon" => "icon-vote",
                "config" => "usercp.vote",
                "name" => lang('myaccount_txt_28', true),
                "desc" => lang('myaccount_txt_29', true),
                "hidden" => false,
            ),
            "lottery" => array(
                "module" => "usercp/lottery",
                "icon" => "icon-lottery",
                "config" => "usercp.lottery",
                "name" => lang('myaccount_txt_77', true),
                "desc" => lang('myaccount_txt_78', true),
                "hidden" => false,
            ),
        ),
    ),
    // Character Panel
    lang('myaccount_txt_30', true) => array(
        "section_active" => true,
        "modules" => array(
            "reset" => array(
                "module" => "usercp/reset",
                "icon" => "icon-reset",
                "config" => "usercp.reset",
                "name" => lang('myaccount_txt_31', true),
                "desc" => lang('myaccount_txt_32', true),
                "hidden" => false,
            ),
            "greset" => array(
                "module" => "usercp/greset",
                "icon" => "icon-greset",
                "config" => "usercp.greset",
                "name" => lang('myaccount_txt_33', true),
                "desc" => lang('myaccount_txt_34', true),
                "hidden" => false,
            ),
            "addstats" => array(
                "module" => "usercp/addstats",
                "icon" => "icon-addstats",
                "config" => "usercp.addstats",
                "name" => lang('myaccount_txt_35', true),
                "desc" => lang('myaccount_txt_36', true),
                "hidden" => false,
            ),
            "resetstats" => array(
                "module" => "usercp/resetstats",
                "icon" => "icon-resetstats",
                "config" => "usercp.resetstats",
                "name" => lang('myaccount_txt_37', true),
                "desc" => lang('myaccount_txt_38', true),
                "hidden" => false,
            ),
            "dualstats" => array(
                "module" => "usercp/dualstats",
                "icon" => "icon-dualstats",
                "config" => "usercp.dualstats",
                "name" => lang('myaccount_txt_39', true),
                "desc" => lang('myaccount_txt_40', true),
                "hidden" => false,
            ),
            "clearskills" => array(
                "module" => "usercp/clearskills",
                "icon" => "icon-resetskilltree",
                "config" => "usercp.clearskills",
                "name" => lang('myaccount_txt_41', true),
                "desc" => lang('myaccount_txt_42', true),
                "hidden" => false,
            ),
            "clearskilltree" => array(
                "module" => "usercp/clearskilltree",
                "icon" => "icon-resetskilltree",
                "config" => "usercp.clearskilltree",
                "name" => lang('myaccount_txt_43', true),
                "desc" => lang('myaccount_txt_44', true),
                "hidden" => false,
            ),
            "dualskilltree" => array(
                "module" => "usercp/dualskilltree",
                "icon" => "icon-dualskilltree",
                "config" => "usercp.dualskilltree",
                "name" => lang('myaccount_txt_45', true),
                "desc" => lang('myaccount_txt_46', true),
                "hidden" => false,
            ),
            "unstuck" => array(
                "module" => "usercp/unstuck",
                "icon" => "icon-unstuck",
                "config" => "usercp.unstuck",
                "name" => lang('myaccount_txt_47', true),
                "desc" => lang('myaccount_txt_48', true),
                "hidden" => false,
            ),
            "clearpk" => array(
                "module" => "usercp/clearpk",
                "icon" => "icon-clearpk",
                "config" => "usercp.clearpk",
                "name" => lang('myaccount_txt_49', true),
                "desc" => lang('myaccount_txt_50', true),
                "hidden" => false,
            ),
            "clearinv" => array(
                "module" => "usercp/clearinv",
                "icon" => "icon-clearinv",
                "config" => "usercp.clearinv",
                "name" => lang('myaccount_txt_51', true),
                "desc" => lang('myaccount_txt_52', true),
                "hidden" => false,
            ),
            "achievements" => array(
                "module" => "usercp/achievements",
                "icon" => "icon-achievements",
                "config" => "usercp.achievements",
                "name" => lang('myaccount_txt_53', true),
                "desc" => lang('myaccount_txt_54', true),
                "hidden" => false,
            ),
        ),
    ),
    // Game Panel
    lang('myaccount_txt_55', true) => array(
        "section_active" => true,
        "modules" => array(
            "exchange" => array(
                "module" => "usercp/exchange",
                "icon" => "icon-exchange",
                "config" => "usercp.exchange",
                "name" => lang('myaccount_txt_56', true),
                "desc" => lang('myaccount_txt_57', true),
                "hidden" => false,
            ),
            "market" => array(
                "module" => "usercp/market",
                "icon" => "icon-market",
                "config" => "usercp.market",
                "name" => lang('myaccount_txt_58', true),
                "desc" => lang('myaccount_txt_59', true),
                "hidden" => false,
            ),
            "webbank" => array(
                "module" => "usercp/webbank",
                "icon" => "icon-webbank",
                "config" => "usercp.webbank",
                "name" => lang('myaccount_txt_60', true),
                "desc" => lang('myaccount_txt_61', true),
                "hidden" => false,
            ),
            "vault" => array(
                "module" => "usercp/vault",
                "icon" => "icon-blacksmith",
                "config" => "usercp.vault",
                "name" => lang('myaccount_txt_62', true),
                "desc" => lang('myaccount_txt_63', true),
                "hidden" => false,
            ),
        ),
    ),
);

$right_menu = array(
    "promo" => array(
        "module" => "usercp/promo",
        "config" => "usercp.promo",
        "name" => lang('myaccount_txt_65', true),
        "class" => 'class="special"',
        "hidden" => false,
    ),
    "balance" => array(
        "module" => "usercp/balance",
        "config" => "usercp.balance",
        "name" => lang('myaccount_txt_66', true),
        "class" => "",
        "hidden" => false,
    ),

    "items" => array(
        "module" => "usercp/items",
        "config" => "usercp.items",
        "name" => lang('myaccount_txt_67', true),
        "class" => "",
        "hidden" => false,
    ),
    "ticket" => array(
        "module" => "ticket",
        "config" => "ticket",
        "name" => lang('myaccount_txt_68', true),
        "class" => "",
        "hidden" => false,
    ),
    "bugtracker" => array(
        "module" => "bugtracker",
        "config" => "bugtracker",
        "name" => lang('myaccount_txt_69', true),
        "class" => "",
        "hidden" => false,
    ),
    "recruit" => array(
        "module" => "usercp/recruit",
        "config" => "usercp.recruit",
        "name" => lang('myaccount_txt_70', true),
        "class" => "",
        "hidden" => false,
    ),
    "changename" => array(
        "module" => "usercp/changename",
        "config" => "usercp.changename",
        "name" => lang('myaccount_txt_71', true),
        "class" => "",
        "hidden" => false,
    ),
    "changeclass" => array(
        "module" => "usercp/changeclass",
        "config" => "usercp.changeclass",
        "name" => lang('changeclass_txt_1', true),
        "class" => "",
        "hidden" => false,
    ),
    "transfercoins" => array(
        "module" => "usercp/transfercoins",
        "config" => "usercp.transfercoins",
        "name" => lang('myaccount_txt_72', true),
        "class" => "",
        "hidden" => false,
    ),
    "transfercharacter" => array(
        "module" => "usercp/transfercharacter",
        "config" => "usercp.transfercharacter",
        "name" => lang('myaccount_txt_73', true),
        "class" => "",
        "hidden" => false,
    ),
    "mypassword" => array(
        "module" => "usercp/mypassword",
        "config" => "usercp.mypassword",
        "name" => lang('myaccount_txt_74', true),
        "class" => "",
        "hidden" => false,
    ),
    "myemail" => array(
        "module" => "usercp/myemail",
        "config" => "usercp.myemail",
        "name" => lang('myaccount_txt_75', true),
        "class" => "",
        "hidden" => false,
    ),
    "logs" => array(
        "module" => "usercp/logs",
        "config" => "usercp.logs",
        "name" => lang('myaccount_txt_76', true),
        "class" => "",
        "hidden" => false,
    ),
);
