<?php
/* ImperiaMuCMS 2.0.7 | Desencriptado por TheKing027 - MTA | Más info: https://muteamargentina.com.ar */

echo "<h2>My Vault Settings</h2>\r\n";
if (check_value($_POST["submit_changes"])) {
    savechanges();
}
$custom = "";
$i = 1;
$customItems = $dB->query_fetch("SELECT * FROM IMPERIAMUCMS_WEB_BANK_CUSTOM");
$end = count($customItems);
foreach ($customItems as $thisItem) {
    if ($i == 1 || $i % 5 == 0) {
        $custom .= "<br>";
    }
    $custom .= $thisItem["ident"] . " = " . $thisItem["name"];
    if ($i < $end) {
        $custom .= ", ";
    }
}
loadModuleConfigs("usercp.vault");
echo "<form action=\"\" method=\"post\">\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Status<br/><span>Enable/disable the vip module.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_1", mconfig("active"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Market Items limit<br/><span>Limit for maximum offers per account</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_85\" value=\"";
echo mconfig("limit");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Is Sell Items<br/><span>Enable/disable adding items to market.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_2", mconfig("is_sell"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Is Delete Items<br/><span>Enable/disable deleting items from vault.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_3", mconfig("is_delete"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Is Upgrade Items<br/><span>Enable/disable upgrading items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_4", mconfig("is_upgrade"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h2>Sell Items</h2>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Enable Platinum Coins<br/><span>Enable/disable selling items for Platinum Coins.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_5", mconfig("platinum"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Gold Coins<br/><span>Enable/disable selling items for Gold Coins.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_6", mconfig("gold"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Silver Coins<br/><span>Enable/disable selling items for Silver Coins.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_7", mconfig("silver"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable WCoinC<br/><span>Enable/disable selling items for WCoinC.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_8", mconfig("WCoinC"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable GoblinPoint<br/><span>Enable/disable selling items for GoblinPoint.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_9", mconfig("GoblinPoint"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Zen<br/><span>Enable/disable selling items for Zen.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_10", mconfig("zen"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Bless<br/><span>Enable/disable selling items for Jewel of Bless.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_11", mconfig("bless"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Soul<br/><span>Enable/disable selling items for Jewel of Soul.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_12", mconfig("soul"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Life<br/><span>Enable/disable selling items for Jewel of Life.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_13", mconfig("life"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Chaos<br/><span>Enable/disable selling items for Jewel of Chaos.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_14", mconfig("chaos"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Harmony<br/><span>Enable/disable selling items for Jewel of Harmony.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_15", mconfig("harmony"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Creation<br/><span>Enable/disable selling items for Jewel of Creation.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_16", mconfig("creation"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Enable Jewel of Guardian<br/><span>Enable/disable selling items for Jewel of Guardian.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_17", mconfig("guardian"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n    </table>\r\n\r\n    <h2>Upgrade Items</h2>\r\n    <table class=\"table table-striped table-bordered table-hover module_config_tables\">\r\n        <tr>\r\n            <th>Allow Ancient Excellent<br/><span>Enable/disable adding excellent options to ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_18", mconfig("enable_anc_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Ancient Skill<br/><span>Enable/disable adding skill to ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_19", mconfig("enable_anc_skill"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Ancient Luck<br/><span>Enable/disable adding luck to ancient items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_20", mconfig("enable_anc_luck"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Ancient Price Ratio<br/><span>Total price of upgrade for ancient items = price * ratio</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_21\" value=\"";
echo mconfig("anc_price_rate");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Socket Excellent<br/><span>Enable/disable adding excellent options to socket items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_22", mconfig("enable_socket_exc"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Socket Skill<br/><span>Enable/disable adding skill to socket items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_23", mconfig("enable_socket_skill"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Socket Luck<br/><span>Enable/disable adding luck to socket items.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_24", mconfig("enable_socket_luck"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Allow Weapons Excellent<br/><span>Enable/disable adding excellent options to weapons.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_25", mconfig("enable_exc_weapon"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Weapons Skill<br/><span>Enable/disable adding skill to weapons.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_26", mconfig("enable_skill_weapon"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Weapons Luck<br/><span>Enable/disable adding luck to weapons.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_27", mconfig("enable_luck_weapon"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Weapons Non-Excellent<br/><span>Enable/disable adding excellent options to non-excellent weapons.<br>\r\n\r\n                    0 = disable, 1 = enable</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_28\" value=\"";
echo mconfig("exc_non_exc_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Random Excellent<br/><span>Enable/disable adding random excellent options to weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    0 = you can select excellent option, 1 = random excellent option</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_29\" value=\"";
echo mconfig("exc_rand_opt_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Max Excellent<br/><span>Maximum allowed excellent option in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 0-6</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_30\" value=\"";
echo mconfig("exc_max_opt_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Random Excellent Prices<br/><span>Prices for random excellent option in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_31\" value=\"";
echo mconfig("exc_rand_price_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #1 Prices<br/><span>Prices for excellent option #1 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_32\" value=\"";
echo mconfig("exc_price1_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #2 Prices<br/><span>Prices for excellent option #2 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_33\" value=\"";
echo mconfig("exc_price2_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #3 Prices<br/><span>Prices for excellent option #3 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_34\" value=\"";
echo mconfig("exc_price3_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #4 Prices<br/><span>Prices for excellent option #4 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_35\" value=\"";
echo mconfig("exc_price4_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #5 Prices<br/><span>Prices for excellent option #5 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_36\" value=\"";
echo mconfig("exc_price5_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent #6 Prices<br/><span>Prices for excellent option #6 in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_37\" value=\"";
echo mconfig("exc_price6_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Excellent Price Types<br/><span>Price types for excellent options in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_38\" value=\"";
echo mconfig("exc_price_type_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Skill Prices<br/><span>Prices for skill in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_39\" value=\"";
echo mconfig("skill_price_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Skill Price Types<br/><span>Price types for skill in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_40\" value=\"";
echo mconfig("skill_price_type_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Luck Prices<br/><span>Prices for luck in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_41\" value=\"";
echo mconfig("luck_price_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Weapons Luck Price Types<br/><span>Price types for luck in weapons.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_42\" value=\"";
echo mconfig("luck_price_type_weapon");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Allow Sets Excellent<br/><span>Enable/disable adding excellent options to Sets.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_43", mconfig("enable_exc_set"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Sets Luck<br/><span>Enable/disable adding luck to Sets.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_44", mconfig("enable_luck_set"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Sets Non-Excellent<br/><span>Enable/disable adding excellent options to non-excellent Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    0 = disable, 1 = enable</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_45\" value=\"";
echo mconfig("exc_non_exc_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Random Excellent<br/><span>Enable/disable adding random excellent options to Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    0 = you can select excellent option, 1 = random excellent option</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_46\" value=\"";
echo mconfig("exc_rand_opt_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Max Excellent<br/><span>Maximum allowed excellent option in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 0-6</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_47\" value=\"";
echo mconfig("exc_max_opt_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Random Excellent Prices<br/><span>Prices for random excellent option in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_48\" value=\"";
echo mconfig("exc_rand_price_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #1 Prices<br/><span>Prices for excellent option #1 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_49\" value=\"";
echo mconfig("exc_price1_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #2 Prices<br/><span>Prices for excellent option #2 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_50\" value=\"";
echo mconfig("exc_price2_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #3 Prices<br/><span>Prices for excellent option #3 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_51\" value=\"";
echo mconfig("exc_price3_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #4 Prices<br/><span>Prices for excellent option #4 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_52\" value=\"";
echo mconfig("exc_price4_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #5 Prices<br/><span>Prices for excellent option #5 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_53\" value=\"";
echo mconfig("exc_price5_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent #6 Prices<br/><span>Prices for excellent option #6 in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_54\" value=\"";
echo mconfig("exc_price6_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Excellent Price Types<br/><span>Price types for excellent options in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_55\" value=\"";
echo mconfig("exc_price_type_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Luck Prices<br/><span>Prices for luck in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_56\" value=\"";
echo mconfig("luck_price_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Sets Luck Price Types<br/><span>Price types for luck in Sets.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_57\" value=\"";
echo mconfig("luck_price_type_set");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Allow Wings Excellent<br/><span>Enable/disable adding excellent options to Wings.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_58", mconfig("enable_exc_wings"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Wings Luck<br/><span>Enable/disable adding luck to Wings.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_59", mconfig("enable_luck_wings"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Wings Non-Excellent<br/><span>Enable/disable adding excellent options to non-excellent Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    0 = disable, 1 = enable</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_60\" value=\"";
echo mconfig("exc_non_exc_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Random Excellent<br/><span>Enable/disable adding random excellent options to Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    0 = you can select excellent option, 1 = random excellent option</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_61\" value=\"";
echo mconfig("exc_rand_opt_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Max Excellent<br/><span>Maximum allowed excellent option in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 0-6</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_62\" value=\"";
echo mconfig("exc_max_opt_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Random Excellent Prices<br/><span>Prices for random excellent option in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_63\" value=\"";
echo mconfig("exc_rand_price_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #1 Prices<br/><span>Prices for excellent option #1 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_64\" value=\"";
echo mconfig("exc_price1_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #2 Prices<br/><span>Prices for excellent option #2 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_65\" value=\"";
echo mconfig("exc_price2_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #3 Prices<br/><span>Prices for excellent option #3 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_66\" value=\"";
echo mconfig("exc_price3_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #4 Prices<br/><span>Prices for excellent option #4 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_67\" value=\"";
echo mconfig("exc_price4_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #5 Prices<br/><span>Prices for excellent option #5 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_68\" value=\"";
echo mconfig("exc_price5_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent #6 Prices<br/><span>Prices for excellent option #6 in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_69\" value=\"";
echo mconfig("exc_price6_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Excellent Price Types<br/><span>Price types for excellent options in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_70\" value=\"";
echo mconfig("exc_price_type_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Luck Prices<br/><span>Prices for luck in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4,tier5] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_71\" value=\"";
echo mconfig("luck_price_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Wings Luck Price Types<br/><span>Price types for luck in Wings.<br>\r\n                    [tier1,tier2,tier3,tier4] => tierX has reference to table [IMPERIAMUCMS_ITEMS].[dbo].[class]<br>\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_72\" value=\"";
echo mconfig("luck_price_type_wings");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>Allow Jewelry Excellent<br/><span>Enable/disable adding excellent options to Jewelry.</span></th>\r\n            <td>\r\n                ";
enabledisableCheckboxes("setting_73", mconfig("enable_exc_jewelry"), "Enabled", "Disabled");
echo "            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Allow Jewelry Non-Excellent<br/><span>Enable/disable adding excellent options to non-excellent Jewelry.<br>\r\n\r\n                    0 = disable, 1 = enable</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_74\" value=\"";
echo mconfig("exc_non_exc_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Random Excellent<br/><span>Enable/disable adding random excellent options to Jewelry.<br>\r\n\r\n                    0 = you can select excellent option, 1 = random excellent option</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_75\" value=\"";
echo mconfig("exc_rand_opt_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Max Excellent<br/><span>Maximum allowed excellent option in Jewelry.<br>\r\n\r\n                    Valid values: 0-6</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_76\" value=\"";
echo mconfig("exc_max_opt_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Random Excellent Prices<br/><span>Prices for random excellent option in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_77\" value=\"";
echo mconfig("exc_rand_price_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #1 Prices<br/><span>Prices for excellent option #1 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_78\" value=\"";
echo mconfig("exc_price1_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #2 Prices<br/><span>Prices for excellent option #2 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_79\" value=\"";
echo mconfig("exc_price2_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #3 Prices<br/><span>Prices for excellent option #3 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_80\" value=\"";
echo mconfig("exc_price3_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #4 Prices<br/><span>Prices for excellent option #4 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_81\" value=\"";
echo mconfig("exc_price4_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #5 Prices<br/><span>Prices for excellent option #5 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_82\" value=\"";
echo mconfig("exc_price5_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent #6 Prices<br/><span>Prices for excellent option #6 in Jewelry.<br>\r\n\r\n                    Valid values: 1-unlimited</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_83\" value=\"";
echo mconfig("exc_price6_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>Jewelry Excellent Price Types<br/><span>Price types for excellent options in Jewelry.<br>\r\n\r\n                    1 = Platinum Coins, 2 = Gold Coins, 3 = Silver Coins, 4 = WCoinC, 5 = GoblinPoint, 6 = Zen, 7 = Jewel of Bless, 8 = Jewel of Soul,<br>\r\n                    9 = Jewel of Life, 10 = Jewel of Chaos, 11 = Jewel of Harmony, 12 = Jewel of Creation, 13 = Jewel of Guardian ";
echo $custom;
echo "</span></th>\r\n            <td>\r\n                <input class=\"form-control\" type=\"text\" name=\"setting_84\" value=\"";
echo mconfig("exc_price_type_jewelry");
echo "\"/>\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <td colspan=\"2\"><input type=\"submit\" name=\"submit_changes\" value=\"Save Changes\" class=\"btn btn-success\"/></td>\r\n        </tr>\r\n    </table>\r\n</form>";
function saveChanges()
{
    
    foreach ($_POST as $setting) {
        if (!check_value($setting)) {
            message("error", "Missing data (complete all fields).");
            return NULL;
        }
    }
    $xmlPath = __PATH_MODULE_CONFIGS__ . "usercp.vault.xml";
    $xml = simplexml_load_file($xmlPath);
    $xml->active = $_POST["setting_1"];
    $xml->is_sell = $_POST["setting_2"];
    $xml->is_delete = $_POST["setting_3"];
    $xml->is_upgrade = $_POST["setting_4"];
    $xml->limit = $_POST["setting_85"];
    $xml->platinum = $_POST["setting_5"];
    $xml->gold = $_POST["setting_6"];
    $xml->silver = $_POST["setting_7"];
    $xml->WCoinC = $_POST["setting_8"];
    $xml->GoblinPoint = $_POST["setting_9"];
    $xml->zen = $_POST["setting_10"];
    $xml->bless = $_POST["setting_11"];
    $xml->soul = $_POST["setting_12"];
    $xml->life = $_POST["setting_13"];
    $xml->chaos = $_POST["setting_14"];
    $xml->harmony = $_POST["setting_15"];
    $xml->creation = $_POST["setting_16"];
    $xml->guardian = $_POST["setting_17"];
    $xml->enable_anc_exc = $_POST["setting_18"];
    $xml->enable_anc_skill = $_POST["setting_19"];
    $xml->enable_anc_luck = $_POST["setting_20"];
    $xml->anc_price_rate = $_POST["setting_21"];
    $xml->enable_socket_exc = $_POST["setting_22"];
    $xml->enable_socket_skill = $_POST["setting_23"];
    $xml->enable_socket_luck = $_POST["setting_24"];
    $xml->enable_exc_weapon = $_POST["setting_25"];
    $xml->enable_skill_weapon = $_POST["setting_26"];
    $xml->enable_luck_weapon = $_POST["setting_27"];
    $xml->exc_non_exc_weapon = $_POST["setting_28"];
    $xml->exc_rand_opt_weapon = $_POST["setting_29"];
    $xml->exc_max_opt_weapon = $_POST["setting_30"];
    $xml->exc_rand_price_weapon = $_POST["setting_31"];
    $xml->exc_price1_weapon = $_POST["setting_32"];
    $xml->exc_price2_weapon = $_POST["setting_33"];
    $xml->exc_price3_weapon = $_POST["setting_34"];
    $xml->exc_price4_weapon = $_POST["setting_35"];
    $xml->exc_price5_weapon = $_POST["setting_36"];
    $xml->exc_price6_weapon = $_POST["setting_37"];
    $xml->exc_price_type_weapon = $_POST["setting_38"];
    $xml->skill_price_weapon = $_POST["setting_39"];
    $xml->skill_price_type_weapon = $_POST["setting_40"];
    $xml->luck_price_weapon = $_POST["setting_41"];
    $xml->luck_price_type_weapon = $_POST["setting_42"];
    $xml->enable_exc_set = $_POST["setting_43"];
    $xml->enable_luck_set = $_POST["setting_44"];
    $xml->exc_non_exc_set = $_POST["setting_45"];
    $xml->exc_rand_opt_set = $_POST["setting_46"];
    $xml->exc_max_opt_set = $_POST["setting_47"];
    $xml->exc_rand_price_set = $_POST["setting_48"];
    $xml->exc_price1_set = $_POST["setting_49"];
    $xml->exc_price2_set = $_POST["setting_50"];
    $xml->exc_price3_set = $_POST["setting_51"];
    $xml->exc_price4_set = $_POST["setting_52"];
    $xml->exc_price5_set = $_POST["setting_53"];
    $xml->exc_price6_set = $_POST["setting_54"];
    $xml->exc_price_type_set = $_POST["setting_55"];
    $xml->luck_price_set = $_POST["setting_56"];
    $xml->luck_price_type_set = $_POST["setting_57"];
    $xml->enable_exc_wings = $_POST["setting_58"];
    $xml->enable_luck_wings = $_POST["setting_59"];
    $xml->exc_non_exc_wings = $_POST["setting_60"];
    $xml->exc_rand_opt_wings = $_POST["setting_61"];
    $xml->exc_max_opt_wings = $_POST["setting_62"];
    $xml->exc_rand_price_wings = $_POST["setting_63"];
    $xml->exc_price1_wings = $_POST["setting_64"];
    $xml->exc_price2_wings = $_POST["setting_65"];
    $xml->exc_price3_wings = $_POST["setting_66"];
    $xml->exc_price4_wings = $_POST["setting_67"];
    $xml->exc_price5_wings = $_POST["setting_68"];
    $xml->exc_price6_wings = $_POST["setting_69"];
    $xml->exc_price_type_wings = $_POST["setting_70"];
    $xml->luck_price_wings = $_POST["setting_71"];
    $xml->luck_price_type_wings = $_POST["setting_72"];
    $xml->enable_exc_jewelry = $_POST["setting_73"];
    $xml->exc_non_exc_jewelry = $_POST["setting_74"];
    $xml->exc_rand_opt_jewelry = $_POST["setting_75"];
    $xml->exc_max_opt_jewelry = $_POST["setting_76"];
    $xml->exc_rand_price_jewelry = $_POST["setting_77"];
    $xml->exc_price1_jewelry = $_POST["setting_78"];
    $xml->exc_price2_jewelry = $_POST["setting_79"];
    $xml->exc_price3_jewelry = $_POST["setting_80"];
    $xml->exc_price4_jewelry = $_POST["setting_81"];
    $xml->exc_price5_jewelry = $_POST["setting_82"];
    $xml->exc_price6_jewelry = $_POST["setting_83"];
    $xml->exc_price_type_jewelry = $_POST["setting_84"];
    $save = $xml->asXML($xmlPath);
    if ($save) {
        message("success", "Settings successfully saved.");
    } else {
        message("error", "There has been an error while saving changes.");
    }
}

?>