<?php
/* ImperiaMuCMS 2.0.7 | Desencriptado por TheKing027 - MTA | Más info: https://muteamargentina.com.ar */

if (!isLoggedIn()) {
    redirect(1, "login");
} else {
    if (!canAccessModule($_SESSION["username"], "donation", "allow")) {
        return NULL;
    }
    if (defined(__RESPONSIVE__) && __RESPONSIVE__ == "TRUE") {
        $breadcrumb = generateBreadcrumb();
        echo "\n    <h3>\n        PayGol\n        " . $breadcrumb . "\n    </h3>";
        if (mconfig("active")) {
            echo "\n    <div class=\"row\">\n        <div class=\"col-xs-12 col-md-6 col-md-offset-3\">\n            <form name=\"pg_frm\" method=\"post\" action=\"https://www.paygol.com/pay\">\n                <div style=\"padding-top: 20px; padding-bottom: 20px;\">\n                    <input type=\"hidden\" name=\"pg_custom\" value=\"" . Encode($_SESSION["username"]) . "\"><p>\n                    <input type=\"hidden\" name=\"pg_serviceid\" value=\"YOUR_SERVICE_ID\">\n                    <input type=\"hidden\" name=\"pg_currency\" value=\"YOUR_CURRENCY\">\n                    <input type=\"hidden\" name=\"pg_name\" value=\"YOUR_NAME\">\n                    <!-- With Dropdown -->\n                    <div class=\"row\">\n                        <label for=\"type\">Select Type:</label>\n                        <select name=\"pg_price\" class=\"form-control\">\n                            <option value=\"1\" selected>1 USD - 10 Gold Coins (1 SMS)</option>\n                            <option value=\"2\">1.50 USD - 16 Gold Coins (1 SMS)</option>\n                            <option value=\"2\">3.50 USD - 40 Gold Coins (2 SMS)</option>\n                        </select>\n                    </div>\n                    <input type=\"hidden\" name=\"pg_return_url\" value=\"" . __BASE_URL__ . "usercp\">\n                    <input type=\"hidden\" name=\"pg_cancel_url\" value=\"" . __BASE_URL__ . "usercp\">\n                    <div class=\"row\" align=\"right\">\n                        <input type=\"submit\" name=\"submit\" class=\"btn btn-warning make-space\" value=\"Continue to PayGol\">\n                    </div>\n                </div>\n            </form>\n        </div>\n    </div>";
        } else {
            message("error", lang("error_47", true));
        }
    } else {
        echo "\n  <div class=\"sub-page-title\">\n    <div id=\"title\">\n      <h1>" . lang("module_titles_txt_3", true) . "<p></p><span></span></h1>\n    </div>\n  </div>\n\n  <div class=\"container_2 account\" align=\"center\">\n    <div class=\"cont-image\">\n      <div class=\"container_3 account_sub_header\">\n        <div class=\"grad\">\n          <div class=\"page-title\"><p>" . lang("donation_txt_3", true) . "</p></div>\n          <div class=\"sub-active-page\">PayGol</div>\n          <a href=\"" . __BASE_URL__ . "donation\">" . lang("donation_txt_6", true) . "</a>\n        </div>\n      </div>\n      <div class=\"page-desc-holder\"></div>";
        if (mconfig("active")) {
            echo "\n    <div class=\"container_3 account_sub_header\">\n        <div class=\"grad\">\n            <div class=\"page-title\">Česká republika</div>\n        </div>\n    </div>\n    <div class=\"container_3 account-wide\" align=\"center\">\n        <form name=\"pg_frm\" method=\"post\" action=\"https://www.paygol.com/pay\">\n            <div style=\"padding-top: 20px; padding-bottom: 20px;\">\n                <input type=\"hidden\" name=\"pg_custom\" value=\"" . Encode($_SESSION["username"]) . "\"><p>\n                <input type=\"hidden\" name=\"pg_serviceid\" value=\"346621\">\n                <input type=\"hidden\" name=\"pg_currency\" value=\"CZK\">\n                <input type=\"hidden\" name=\"pg_name\" value=\"Podpora ExcellentMU CZ\">\n                <!-- With Dropdown -->\n                <div class=\"row\">\n                    <label for=\"type\">Select Type:</label>\n                    <select name=\"pg_price\" styled=\"true\" id=\"select-style-2\" style=\"display: none;\">\n                        <option value=\"1\" selected>30.00 Kč - 4 kredity (1 SMS)</option>\n                        <option value=\"2\">50.00 Kč - 7 kreditov (1 SMS)</option>\n                        <option value=\"3\">99.00 Kč - 14 kreditov (1 SMS)</option>\n                        <option value=\"4\">198.00 Kč - 29 kreditov (2 SMS)</option>\n                        <option value=\"5\">297.00 Kč - 45 kreditov (3 SMS)</option>\n                    </select>\n                </div>\n                <input type=\"hidden\" name=\"pg_return_url\" value=\"http://excellentmu.cz/usercp\">\n                <input type=\"hidden\" name=\"pg_cancel_url\" value=\"http://excellentmu.cz/usercp\">\n                <div class=\"row\" align=\"right\">\n                    <input type=\"submit\" name=\"submit\" value=\"Continue to PayGol\">\n                </div>\n            </div>\n        </form>\n    </div>";
            echo "<br /><br /><br />\n    <div class=\"container_3 account_sub_header\">\n        <div class=\"grad\">\n            <div class=\"page-title\">Slovensko</div>\n        </div>\n    </div>\n    <div class=\"container_3 account-wide\" align=\"center\">\n        <form name=\"pg_frm\" method=\"post\" action=\"https://www.paygol.com/pay\">\n            <div style=\"padding-top: 20px; padding-bottom: 20px;\">\n                <input type=\"hidden\" name=\"pg_custom\" value=\"" . Encode($_SESSION["username"]) . "\"><p>\n                <input type=\"hidden\" name=\"pg_serviceid\" value=\"346622\">\n                <input type=\"hidden\" name=\"pg_currency\" value=\"EUR\">\n                <input type=\"hidden\" name=\"pg_name\" value=\"Podpora ExcellentMU SK\">\n                <!-- With Dropdown -->\n                <div class=\"row\">\n                    <label for=\"type\">Select Type:</label>\n                    <select name=\"pg_price\" styled=\"true\" id=\"select-style-2\" style=\"display: none;\">\n                        <option value=\"1\" selected> 1.20 Eur - 4 kredity (1 SMS)</option>\n                        <option value=\"2\"> 1.60 Eur - 6 kreditov (1 SMS)</option>\n                        <option value=\"3\"> 3.20 Eur - 13 kreditov (2 SMS)</option>\n                        <option value=\"4\"> 6.40 Eur - 27 kreditov (4 SMS)</option>\n                        <option value=\"5\"> 9.60 Eur - 42 kreditov (6 SMS)</option>\n                    </select>\n                </div>\n                <input type=\"hidden\" name=\"pg_return_url\" value=\"http://excellentmu.cz/usercp\">\n                <input type=\"hidden\" name=\"pg_cancel_url\" value=\"http://excellentmu.cz/usercp\">\n                <div class=\"row\" align=\"right\">\n                    <input type=\"submit\" name=\"submit\" value=\"Continue to PayGol\">\n                </div>\n            </div>\n        </form>\n    </div>";
        } else {
            message("error", lang("error_47", true));
        }
        echo "\n    </div>\n  </div>\n\t";
    }
}

?>